language: cpp
dist: xenial

matrix:
  include:
    - os: linux
      compiler: gcc

    - os: linux
      compiler: clang

    - os: osx

addons:
  homebrew:
    packages:
      - qt

before_install:

install:
  - export QT_SELECT=5
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y qtbase5-dev; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew link --force qt; fi
  - qmake -v

script:
  - qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make -j 2
  - cd quackleio && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make -j 2
  - cd ..
  - cd quacker && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make -j 2
  - cd ..
  - cd encodeleaves && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make -j 2
  - cd ..
  - cd gaddagize && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make -j 2
  - cd ..
  - cd makegaddag && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make -j 2
  - cd ..
  - cd makeminidawg && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make -j 2
  - cd ..
  - cd quackleio/iotest && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make -j 2
  - cd ../..
  - cd test && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make -j 2
  - cd ..
