language: cpp
dist: trusty
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - gcc
    - g++
    - clang
    - qtbase5-dev
    - qt5-qmake
script: 
  - qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd quackleio && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ..
  - cd quacker && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ..
  - cd encodeleaves && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ..
  - cd gaddagize && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ..
  - cd makegaddag && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ..
  - cd makeminidawg && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ..
  - cd quackleio/iotest && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ../..
  - cd test && qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make
  - cd ..
